- name: user
  user: name={{cs_user}} state=present

- name: system requirements
  apt:
    name:
      - build-essential
      - cpanminus
      - gcc
      - git
      - libpq-dev
      - libssl-dev
      - make
      - sudo
      - zlib1g-dev
      - rsync
      - atop
      - htop
      - docker.io
    state: latest
    update_cache: yes

- name: git name
  git_config: name="user.name" value="{{cs_user}}" scope="global"

- name: git email
  git_config: name="user.email" value="{{cs_user}}@hackerdom.ru" scope="global"

#- name: repo stash
#  command: git stash chdir="{{cs_dir}}"
#  become: yes
#  become_user: "{{cs_user}}"
#  ignore_errors: yes
#  register: g
#  changed_when: "g.stdout.find('No local changes') == -1"
#  tags: update

- name: repo
  git: repo=https://github.com/HackerDom/checksystem.git dest={{cs_dir}}
  become: yes
  become_user: "{{cs_user}}"
  tags: update

#- name: repo unstash
#  command: git stash pop chdir="{{cs_dir}}"
#  become: yes
#  become_user: "{{cs_user}}"
#  ignore_errors: yes
#  when: "g.stdout.find('No local changes') == -1"
#  tags: update

- name: config
  template: src=c_s.conf.j2 dest={{cs_dir}}/c_s.conf owner={{cs_user}} group={{cs_user}}
  tags: update

- name: perl modules
  command: cpanm -n --installdeps {{cs_dir}}
  register: r
  changed_when: "r.stdout.find('Found dependencies') != -1"
