services:
  app:
    build: .
    ports:
      - 5051:8080
    restart: always
    depends_on:
      - postgres
    stop_grace_period: 3s
    mem_limit: 4G
    pids_limit: 1000

  postgres:
    image: postgres:14.1-alpine
    restart: always
    mem_limit: 4G
    memswap_limit: 4G
    pids_limit: 1000
    volumes:
        - data:/var/lib/postgresql/data/
        - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=6531
      - POSTGRES_USER=postgres

volumes:
    data:
