version: '2.2'
services:
  ctfland:
    image: ctfland
    build: .
    ports:
     - "7777:80"

    restart: always
    depends_on:
      - db
    env_file:
      - ./variables.env
      
    stop_grace_period: 1s
    pids_limit: 40
    cpus: 1.5
    mem_limit: 2G
    memswap_limit: 1G


  db:
    image: 'cr.yandex/crpogk7287k25tqmrogj/postgres:latest'
    restart: always
    env_file:
      - ./variables.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
