version: '3.7'
services:
  resoccessor:
    image: resoccessor
    build: .
    ports:
      - "3000:3000"

    restart: always
    depends_on:
      - redis

    stop_grace_period: 1s

  redis:
    image: 'cr.yandex/crpogk7287k25tqmrogj/redis:6.2.6-alpine'
    restart: always
