version: '3.7'
services:
  ctfland:
    image: resoccessor
    build: .
    ports:
      - "3000:3000"

    restart: always
    depends_on:
      - redis

    stop_grace_period: 1s

  redis:
    image: 'redis:6.2.6-alpine'
    restart: always
    volumes:
      - ./data/redis:/data
